#version 460

#include "extensions.glsl"
#include "utils.glsl"

layout(binding = 0) uniform sampler2D inputTex;
layout(rgba16f, binding = 1) restrict writeonly uniform image2D frameBuffer;

layout(push_constant, scalar) uniform constants {
    i32 inputMip;
} pcs;

float karis(vec3 inputColor) {
	return 1.0f / (1.0f + dot(inputColor, vec3(0.2126f, 0.7152f, 0.0722f)));
}

vec3 fireflyFilter(vec3 group1, vec3 group2, vec3 group3, vec3 group4, vec3 group5) {
	return group1 * karis(group1) + group2 * karis(group2) + group3 * karis(group3) + group4 * karis(group4) + group5 * karis(group5);
}

layout (local_size_x = 8, local_size_y = 8) in;
void main() {
	ivec2 dimensions = imageSize(frameBuffer);
	vec2 uv = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5f)) / dimensions;
	vec2 texelSize = 1.0f / textureSize(inputTex, 0);

	vec3 a = textureLod(inputTex, uv + texelSize * vec2(-2.0f,  2.0f), 0).rgb;
	vec3 b = textureLod(inputTex, uv + texelSize * vec2( 0.0f,  2.0f), 0).rgb;
	vec3 c = textureLod(inputTex, uv + texelSize * vec2( 2.0f,  2.0f), 0).rgb;
	vec3 d = textureLod(inputTex, uv + texelSize * vec2(-2.0f,  0.0f), 0).rgb;
	vec3 e = textureLod(inputTex, uv + texelSize * vec2( 0.0f,  0.0f), 0).rgb;
	vec3 f = textureLod(inputTex, uv + texelSize * vec2( 2.0f,  0.0f), 0).rgb;
	vec3 g = textureLod(inputTex, uv + texelSize * vec2(-2.0f, -2.0f), 0).rgb;
	vec3 h = textureLod(inputTex, uv + texelSize * vec2( 0.0f, -2.0f), 0).rgb;
	vec3 i = textureLod(inputTex, uv + texelSize * vec2( 2.0f, -2.0f), 0).rgb;
	vec3 j = textureLod(inputTex, uv + texelSize * vec2(-1.0f,  1.0f), 0).rgb;
	vec3 k = textureLod(inputTex, uv + texelSize * vec2( 1.0f,  1.0f), 0).rgb;
	vec3 l = textureLod(inputTex, uv + texelSize * vec2(-1.0f, -1.0f), 0).rgb;
	vec3 m = textureLod(inputTex, uv + texelSize * vec2( 1.0f, -1.0f), 0).rgb;

	vec3 color = vec3(0.0f);

	switch(pcs.inputMip) {
		case 0:
			color = fireflyFilter(
				(a + b + d + e) * 0.03125f,
				(b + c + e + f) * 0.03125f,
				(d + e + g + h) * 0.03125f,
				(e + f + h + i) * 0.03125f,
				(j + k + l + m) * 0.125f
			);
			break;
		default:
			color = (a + c + g + i) * 0.03125f + (b + d + f + h) * 0.0625f + (e + j + k + l + m) * 0.125f;
			break;
	}

	imageStore(frameBuffer, ivec2(gl_GlobalInvocationID.xy), vec4(color, 1.0f));
}