#version 460

#include "extensions.glsl"
#include "texture_heap.glsl"
#include "utils.glsl"

layout(push_constant, scalar) uniform constants {
	u32 inputTex;
	u32 frameBuffer;
} pcs;

layout (local_size_x = 8, local_size_y = 8) in;
void main() {
	ivec2 dimensions = imageSize(UNPACK_IMG_2D(pcs.frameBuffer));
	vec2 uv = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5f)) / dimensions;
	vec2 texelSize = 1.5f / textureSize(UNPACK_TEX_2D(pcs.inputTex), 0);

	vec3 a = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2(-1.0f,  1.0f), 0).rgb;
	vec3 b = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2( 0.0f,  1.0f), 0).rgb;
	vec3 c = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2( 1.0f,  1.0f), 0).rgb;
	vec3 d = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2(-1.0f,  0.0f), 0).rgb;
	vec3 e = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2( 0.0f,  0.0f), 0).rgb;
	vec3 f = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2( 1.0f,  0.0f), 0).rgb;
	vec3 g = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2(-1.0f, -1.0f), 0).rgb;
	vec3 h = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2( 0.0f, -1.0f), 0).rgb;
	vec3 i = textureLod(UNPACK_TEX_2D(pcs.inputTex), uv + texelSize * vec2( 1.0f, -1.0f), 0).rgb;

	vec3 color = imageLoad(UNPACK_IMG_2D(pcs.frameBuffer), ivec2(gl_GlobalInvocationID.xy)).rgb;
	color += ((a + c + g + i) + (b + d + f + h) * 2.0f + e * 4.0f) / 16.0f;
	imageStore(UNPACK_IMG_2D(pcs.frameBuffer), ivec2(gl_GlobalInvocationID.xy), vec4(color, 1.0f));
}