#version 460

#include "extensions.glsl"
#include "texture_heap.glsl"
#include "utils.glsl"

layout(push_constant, scalar) uniform constants {
	u32 lowerMip;
	u32 higherMip;
} pcs;

layout(local_size_x = 8, local_size_y = 8) in;
void main() {
    vec4 pixel = vec4(0.0f);

    pixel += unpacke5bgr9(imageLoad(UNPACK_UIMG_CUBE(pcs.lowerMip), ivec3(gl_GlobalInvocationID.xy * 2 + uvec2(0, 0), gl_GlobalInvocationID.z)).r);
    pixel += unpacke5bgr9(imageLoad(UNPACK_UIMG_CUBE(pcs.lowerMip), ivec3(gl_GlobalInvocationID.xy * 2 + uvec2(0, 1), gl_GlobalInvocationID.z)).r);
    pixel += unpacke5bgr9(imageLoad(UNPACK_UIMG_CUBE(pcs.lowerMip), ivec3(gl_GlobalInvocationID.xy * 2 + uvec2(1, 0), gl_GlobalInvocationID.z)).r);
    pixel += unpacke5bgr9(imageLoad(UNPACK_UIMG_CUBE(pcs.lowerMip), ivec3(gl_GlobalInvocationID.xy * 2 + uvec2(1, 1), gl_GlobalInvocationID.z)).r);

    imageStore(UNPACK_UIMG_CUBE(pcs.higherMip), ivec3(gl_GlobalInvocationID), uvec4(packe5bgr9(pixel / 4.0f)));
}