#version 460

#include "extensions.glsl"
#include "texture_heap.glsl"
#include "utils.glsl"

#define PI 3.141593f

layout(push_constant, scalar) uniform constants {
	u32 skyboxTex;
	u32 outputTex;
} pcs;

layout(local_size_x = 8, local_size_y = 8) in;
void main() {
    vec3 pos = 2.0f * vec3(gl_GlobalInvocationID.xy / vec2(imageSize(UNPACK_UIMG_CUBE(pcs.outputTex))), 1.0f) - 1.0f;
	vec3 faces[6] = {
		vec3( pos.z, -pos.y, -pos.x),
		vec3(-pos.z, -pos.y,  pos.x),
		vec3( pos.x,  pos.z,  pos.y),
		vec3( pos.x, -pos.z, -pos.y),
		vec3( pos.x, -pos.y,  pos.z),
		vec3(-pos.x, -pos.y, -pos.z)
	};
	vec3 normal = normalize(faces[gl_GlobalInvocationID.z]);

    vec3 irradiance = vec3(0.0f);
    vec3 up = vec3(0.0f, 1.0f, 0.0f);
    vec3 right = normalize(cross(up, normal));
    up = normalize(cross(normal, right));

    // passed into texturelod, sample from the mip that matches the texel count of the irradiance texture
    f32 mipLevel = countMips(textureSize(UNPACK_TEX_CUBE(pcs.skyboxTex), 0)) - countMips(imageSize(UNPACK_UIMG_CUBE(pcs.outputTex)));

    const f32 sampleDelta = 0.025f;
    f32 numSamples = 0.0f;

    for(f32 phi = 0.0f; phi < PI * 2.0f; phi += sampleDelta) {
        for(f32 theta = 0.0f; theta < PI * 0.5f; theta += sampleDelta) {
            vec3 tangentSample = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
            vec3 sampleDir = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal; 
            irradiance += textureLod(UNPACK_TEX_CUBE(pcs.skyboxTex), sampleDir, mipLevel).rgb * cos(theta) * sin(theta);
            numSamples++;
        }
    }

    imageStore(UNPACK_UIMG_CUBE(pcs.outputTex), ivec3(gl_GlobalInvocationID), uvec4(packe5bgr9(vec4(irradiance * PI / numSamples, 1.0f))));
}