#version 460

#include "extensions.glsl"
#include "texture_heap.glsl"
#include "types.glsl"

layout(push_constant, scalar) uniform constants {
    u32 lowerMip;
    u32 higherMip;
} pcs;

layout(local_size_x = 8, local_size_y = 8) in;
void main() {
    vec4 pixel = vec4(0.0f);

    pixel += imageLoad(UNPACK_IMG_2D(pcs.lowerMip), ivec2(gl_GlobalInvocationID.xy * 2 + uvec2(0, 0)));
    pixel += imageLoad(UNPACK_IMG_2D(pcs.lowerMip), ivec2(gl_GlobalInvocationID.xy * 2 + uvec2(0, 1)));
    pixel += imageLoad(UNPACK_IMG_2D(pcs.lowerMip), ivec2(gl_GlobalInvocationID.xy * 2 + uvec2(1, 0)));
    pixel += imageLoad(UNPACK_IMG_2D(pcs.lowerMip), ivec2(gl_GlobalInvocationID.xy * 2 + uvec2(1, 1)));

    imageStore(UNPACK_IMG_2D(pcs.higherMip), ivec2(gl_GlobalInvocationID), pixel / 4.0f);
}