#version 460

#include "extensions.glsl"
#include "texture_heap.glsl"
#include "utils.glsl"

layout(push_constant, scalar) uniform constants {
    u32 frameBuffer;
    u32 bloomBuffer;
    u32 tonemapper;
} pcs;

layout(local_size_x = 8, local_size_y = 8) in;
void main() {
    vec3 color = imageLoad(UNPACK_IMG_2D(pcs.frameBuffer), ivec2(gl_GlobalInvocationID)).rgb;
    color = mix(color, imageLoad(UNPACK_IMG_2D(pcs.bloomBuffer), ivec2(gl_GlobalInvocationID)).rgb, 0.04f);

    switch(pcs.tonemapper) {
        case 0:
            color = linearToSrgb(aces(color));
            break;
        case 1:
            color = agx(color);
            break;
        case 2:
            color = linearToSrgb(khronos(color));
            break;
        default:
            color = linearToSrgb(reinhard(color));
            break;
    }

    imageStore(UNPACK_IMG_2D(pcs.frameBuffer), ivec2(gl_GlobalInvocationID), vec4(color, 1.0f));
}