#version 460

#include "extensions.glsl"
#include "texture_heap.glsl"
#include "utils.glsl"

#include "shared/oitnode.h"


layout(buffer_reference, scalar) restrict readonly buffer OITBuffer {
    OITNode nodes[];
};

layout(push_constant, scalar) uniform constants {
    OITBuffer oitBuffer;
    u32 frameBuffer;
} pcs;

layout(local_size_x = 8, local_size_y = 8) in;
void main() {
    uvec2 frameBufferSize = uvec2(imageSize(UNPACK_IMG_2D(pcs.frameBuffer)));
    vec3 color = imageLoad(UNPACK_IMG_2D(pcs.frameBuffer), ivec2(gl_GlobalInvocationID)).rgb;
    u32 baseIndex = (gl_GlobalInvocationID.y * frameBufferSize.x + gl_GlobalInvocationID.x) * 4;

    if(gl_GlobalInvocationID.x < frameBufferSize.x && gl_GlobalInvocationID.y < frameBufferSize.y) {
        for(u32 i = 4; i > 0; i--) {
            OITNode cur = pcs.oitBuffer.nodes[baseIndex + i - 1];
            if(cur.packedDepthTransmittance != 0) {
                color = mix(unpacke5bgr9(cur.packedColor).rgb, color, unpackTransmittance(cur.packedDepthTransmittance));
            }
        }
    }

    imageStore(UNPACK_IMG_2D(pcs.frameBuffer), ivec2(gl_GlobalInvocationID), vec4(color, 1.0f));
}