#version 460

#include "extensions.glsl"
#include "texture_heap.glsl"
#include "utils.glsl"

#include "shared/oitnode.h"

layout(push_constant, scalar) uniform constants {
    u32 swapchain;
    u32 uiBuffer;
} pcs;

layout(local_size_x = 8, local_size_y = 8) in;
void main() {
    vec3 color = imageLoad(UNPACK_IMG_2D(pcs.swapchain), ivec2(gl_GlobalInvocationID)).rgb;
    vec4 uiColor = imageLoad(UNPACK_IMG_2D(pcs.uiBuffer), ivec2(gl_GlobalInvocationID));

    imageStore(UNPACK_IMG_2D(pcs.swapchain), ivec2(gl_GlobalInvocationID), vec4(mix(color, uiColor.rgb, uiColor.a), 1.0f));
}