#version 460

#include "extensions.glsl"

layout(binding = 0) uniform sampler2D Source;
layout(binding = 1) restrict writeonly uniform image2D Output;

layout(local_size_x = 8, local_size_y = 8) in;
void main() {
   vec2 size = vec2(textureSize(Source, 0));
   vec2 vTexCoord = (vec2(gl_GlobalInvocationID) + 0.5f) / size;

   imageStore(Output, ivec2(gl_GlobalInvocationID), clamp(textureLod(Source, vTexCoord, 0), vec4(0.0f), vec4(1.0f)));
}