#version 460

#include "extensions.glsl"
#include "utils.glsl"

layout(binding = 0) uniform sampler2D inputTex;
layout(rgba16f, binding = 1) restrict uniform image2D frameBuffer;

layout(push_constant, scalar) uniform constants {
    i32 inputMip;
} pcs;

float karis(vec3 inputColor) {
	return 1.0f / (1.0f + dot(inputColor, vec3(0.2126f, 0.7152f, 0.0722f)));
}

vec3 fireflyFilter(vec3 group1, vec3 group2, vec3 group3, vec3 group4, vec3 group5) {
	return group1 * karis(group1) + group2 * karis(group2) + group3 * karis(group3) + group4 * karis(group4) + group5 * karis(group5);
}

layout (local_size_x = 8, local_size_y = 8) in;
void main() {
	ivec2 dimensions = imageSize(frameBuffer);
	vec2 uv = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5f)) / dimensions;
	vec2 texelSize = 1.5f / textureSize(inputTex, 0);

	vec3 a = textureLod(inputTex, uv + texelSize * vec2(-1.0f,  1.0f), 0).rgb;
	vec3 b = textureLod(inputTex, uv + texelSize * vec2( 0.0f,  1.0f), 0).rgb;
	vec3 c = textureLod(inputTex, uv + texelSize * vec2( 1.0f,  1.0f), 0).rgb;
	vec3 d = textureLod(inputTex, uv + texelSize * vec2(-1.0f,  0.0f), 0).rgb;
	vec3 e = textureLod(inputTex, uv + texelSize * vec2( 0.0f,  0.0f), 0).rgb;
	vec3 f = textureLod(inputTex, uv + texelSize * vec2( 1.0f,  0.0f), 0).rgb;
	vec3 g = textureLod(inputTex, uv + texelSize * vec2(-1.0f, -1.0f), 0).rgb;
	vec3 h = textureLod(inputTex, uv + texelSize * vec2( 0.0f, -1.0f), 0).rgb;
	vec3 i = textureLod(inputTex, uv + texelSize * vec2( 1.0f, -1.0f), 0).rgb;

	vec3 color = imageLoad(frameBuffer, ivec2(gl_GlobalInvocationID.xy)).rgb;
	color += ((a + c + g + i) + (b + d + f + h) * 2.0f + e * 4.0f) / 16.0f;
	imageStore(frameBuffer, ivec2(gl_GlobalInvocationID.xy), vec4(color, 1.0f));
}