#version 460

#include "extensions.glsl"
#include "utils.glsl"

layout(rgba16f, binding = 0) uniform restrict readonly image2D framebuffer;
layout(rgba16f, binding = 1) uniform restrict readonly image2D bloomBuffer;
layout(binding = 2) uniform restrict writeonly image2D swapchain;

layout(push_constant, scalar) uniform constants {
    u32 tonemapper;
} pcs;

layout(local_size_x = 8, local_size_y = 8) in;
void main() {
    vec3 color = imageLoad(framebuffer, ivec2(gl_GlobalInvocationID)).rgb;

    switch(pcs.tonemapper) {
        case 0:
            color = linearToSrgb(aces(color));
            break;
        case 1:
            color = agx(color);
            break;
        case 2:
            color = linearToSrgb(khronos(color));
            break;
        default:
            color = linearToSrgb(reinhard(color));
            break;
    }

    imageStore(swapchain, ivec2(gl_GlobalInvocationID), vec4(color, 1.0f));
}